name: push-ci
on: push

jobs:
  npm-run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version-file: package.json
      - run: npm install
      - run: echo '{}' > local.json
      - run: npm run ci
