name: push-ci
on: push

jobs:
  npm-run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e
      - uses: actions/setup-node@60edb5d
        with:
          node-version-file: package.json
      - run: npm install
      - run: echo '{}' > local.json
      - run: npm run ci
